image: node:latest

stages:
  - server-testing
  - react-testing
  - react-build
  - server-deploy
  - react-deploy


variables:
  POSTGRES_DB: capstone_test
  POSTGRES_USER: postgre
  POSTGRES_PASSWORD: postgre
  POSTGRES_HOST: postgres

server-testing:
  services:
    - postgres:latest

  before_script:
    - cd express
    - yarn install
    - yarn knex migrate:latest --env test
  stage: server-testing
  script:
    - yarn jest

react-testing:
  before_script:
    - cd react-app
    - yarn install
  stage: react-testing
  script:
    - CI=true yarn test

react-build:
  stage: react-build
  before_script:
    - cd react-app/
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - react/build

server-deploy:
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private.pem
    - chmod 400 private.pem
    - ssh-add private.pem > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H 54.255.120.244 > ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  stage: server-deploy
  only:
    - production
  script:
    - ssh ubuntu@54.255.120.244 
        "cd final-capstone-project;
          git pull origin master;
          git checkout production;
          git pull origin production;
          cd express;
          yarn install;
          yarn knex migrate:latest --env production;
          forever restart index.js;"
  
react-deploy:
  image: "python:3.6"
  stage: react-deploy
  before_script:
    - pip install awscli
  dependencies:
    - react-build
  only:
    - production
  script:
    - aws s3 sync react/build s3://${BUCKET_NAME} --delete
    - aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_DISTRIBUTION} --paths "/*"